# Generated by Django 5.1 on 2024-09-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_myusermodel_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusermodel',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='myusermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
