# Generated by Django 5.1 on 2024-09-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_useraddressmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusermodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
