# Generated by Django 5.1 on 2024-09-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_myusermodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddressModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('last_update', models.DateField()),
            ],
        ),
    ]
