# Generated by Django 5.1 on 2024-09-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_useraddressmodeldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddressmodeldata',
            name='last_update',
            field=models.DateField(auto_now_add=True),
        ),
    ]
